/*
# このタブ以外を閉じるマクロ

# 連絡先
https://github.com/ohtorii/everything	<br>
http://d.hatena.ne.jp/ohtorii/			<br>
https://twitter.com/ohtorii				<br>
*/
call main;
endmacro;

main:
	##i = tabtotal - 1;
	while( 0 <= ##i ) {
		##handle = gettabhandle( true, 0, ##i );
		if( ##handle == hidemaruhandle(0) ) {
			//自分自身
		} else {
			if( updated[##handle] ) {
				//message filename2[##handle] + "更新されています。";
			}else{
				closehidemaru ##handle;
			}
		}
		##i = ##i - 1;
	}
	return ;
